import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '../app/components/shared/Navbar'
import ParticlesBg from './components/shared/Particles/ParticlesBg'
import Footer from './components/shared/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
<ParticlesBg></ParticlesBg>
        <Navbar/>
        
        {children}
        <Footer></Footer>


        
        </body>
    </html>
  )
}
